with raw_data as (
    select 
    coalesce(event.value:sport_event.id::string, 'unknown') as event_id,
    coalesce(team.value:id::string, 'unknown') as competitor_id,
    coalesce(player.value:id::string, 'unknown') as player_id,
    coalesce(player.value:name::string, 'unknown') as player_name,
    coalesce(player.value:starter::boolean, false) as starter, 
    coalesce(player.value:statistics.assists::int, 0) as assists,
    coalesce(player.value:statistics.chances_created::int, 0) as chances_created,
    coalesce(player.value:statistics.clearances::int, 0) as clearances,
    coalesce(player.value:statistics.corner_kicks::int, 0) as corner_kicks,
    coalesce(player.value:statistics.crosses_successful::int, 0) as crosses_successful,
    coalesce(player.value:statistics.crosses_total::int, 0) as crosses_total,
    coalesce(player.value:statistics.defensive_blocks::int, 0) as defensive_blocks,
    coalesce(player.value:statistics.diving_saves::int, 0) as diving_saves,
    coalesce(player.value:statistics.dribbles_completed::int, 0) as dribbles_completed,
    coalesce(player.value:statistics.fouls_committed::int, 0) as fouls_committed,
    coalesce(player.value:statistics.goals_by_head::int, 0) as goals_by_head,
    coalesce(player.value:statistics.goals_by_penalty::int, 0) as goals_by_penalty,
    coalesce(player.value:statistics.goals_conceded::int, 0) as goals_conceded,
    coalesce(player.value:statistics.goals_scored::int, 0) as goals_scored,
    coalesce(player.value:statistics.interceptions::int, 0) as interceptions,
    coalesce(player.value:statistics.long_passes_successful::int, 0) as long_passes_successful,
    coalesce(player.value:statistics.long_passes_total::int, 0) as long_passes_total,
    coalesce(player.value:statistics.long_passes_unsuccessful::int, 0) as long_passes_unsuccessful,
    coalesce(player.value:statistics.loss_of_possession::int, 0) as loss_of_possession,
    coalesce(player.value:statistics.minutes_played::int, 0) as minutes_played,
    coalesce(player.value:statistics.offsides::int, 0) as offsides,
    coalesce(player.value:statistics.own_goals::int, 0) as own_goals,
    coalesce(player.value:statistics.passes_successful::int, 0) as passes_successful,
    coalesce(player.value:statistics.passes_total::int, 0) as passes_total,
    coalesce(player.value:statistics.passes_unsuccessful::int, 0) as passes_unsuccessful,
    coalesce(player.value:statistics.penalties_faced::int, 0) as penalties_faced,
    coalesce(player.value:statistics.penalties_missed::int, 0) as penalties_missed,
    coalesce(player.value:statistics.penalties_saved::int, 0) as penalties_saved,
    coalesce(player.value:statistics.red_cards::int, 0) as red_cards,
    coalesce(player.value:statistics.shots_blocked::int, 0) as shots_blocked,
    coalesce(player.value:statistics.shots_faced_saved::int, 0) as shots_faced_saved,
    coalesce(player.value:statistics.shots_faced_total::int, 0) as shots_faced_total,
    coalesce(player.value:statistics.shots_off_target::int, 0) as shots_off_target,
    coalesce(player.value:statistics.shots_on_target::int, 0) as shots_on_target,
    coalesce(player.value:statistics.substituted_in::int, 0) as substituted_in,
    coalesce(player.value:statistics.substituted_out::int, 0) as substituted_out,
    coalesce(player.value:statistics.tackles_successful::int, 0) as tackles_successful,
    coalesce(player.value:statistics.tackles_total::int, 0) as tackles_total,
    coalesce(player.value:statistics.was_fouled::int, 0) as was_fouled,
    coalesce(player.value:statistics.yellow_cards::int, 0) as yellow_cards,
    coalesce(player.value:statistics.yellow_red_cards::int, 0) as yellow_red_cards
    from {{ source('liverpool', 'sportradar_data') }},
    lateral flatten(input => data:summaries) event,
    lateral flatten(input => event.value:statistics.totals.competitors) team,
    lateral flatten(input => team.value:players) player
)

select
    event_id,
    competitor_id,
    player_id,
    player_name,
    starter,
    assists,
    chances_created,
    clearances,
    corner_kicks,
    crosses_successful,
    crosses_total,
    defensive_blocks,
    diving_saves,
    dribbles_completed,
    fouls_committed,
    goals_by_head,
    goals_by_penalty,
    goals_conceded,
    goals_scored,
    interceptions,
    long_passes_successful,
    long_passes_total,
    long_passes_unsuccessful,
    loss_of_possession,
    minutes_played,
    offsides,
    own_goals,
    passes_successful,
    passes_total,
    passes_unsuccessful,
    penalties_faced,
    penalties_missed,
    penalties_saved,
    red_cards,
    shots_blocked,
    shots_faced_saved,
    shots_faced_total,
    shots_off_target,
    shots_on_target,
    substituted_in,
    substituted_out,
    tackles_successful,
    tackles_total,
    was_fouled,
    yellow_cards,
    yellow_red_cards
from raw_data